### PR TITLE
Update to the test file of the TCS34725 color sensor 

### PR DESCRIPTION
**Pull request by silviaCC**
Added more examples of how to read the data form the color sensor in `tcs34725_simpletest.py.`  

Also added a comment explaining the gamma correction calculations that are done on the raw values from the sensor in `color_rgb_bytes` from `adafruit_tcs34725.py`.

### CODE REVIEW

**Comment by jposada202020** [comment]
@silviaCC The CI is failing on Black and Pylint, could you make sure you've run Pylint and Black locally on your code. You can do this manually or using pre-commit. Instructions are available here: https://adafru.it/check-your-code

Thanks :)

**Comment by jposada202020** [comment]
@jposada202020 I have just saw you comment in the discord channel, ping me if you need any help..

**Comment by silviaCC** [comment]
@jposada202020  If you could message me in discord, I would really appreciate the help, thank you!

**Comment by jposada202020** [comment]
@silviaCC so right know the CI is only complaining about black, this is fairly easy to solve if we run black on the files. could you try it, also what I would do in the meantime is that I will grab your files and do the same..

**Comment by jposada202020** [comment]
@silviaCC according to the changes. you could change the `tcs34725_simpletest.py` file with this, and I think we will be good (I hope LOL)
```python
# SPDX-FileCopyrightText: 2021 ladyada for Adafruit Industries
# SPDX-License-Identifier: MIT

# Simple demo of the TCS34725 color sensor.
# Will detect the color from the sensor and print it out every second.
import time
import board
import adafruit_tcs34725


# Create sensor object, communicating over the board's default I2C bus
i2c = board.I2C()  # uses board.SCL and board.SDA
sensor = adafruit_tcs34725.TCS34725(i2c)

# Change sensor integration time to values between 2.4 and 614.4 milliseconds
# sensor.integration_time = 150

# Change sensor gain to 1, 4, 16, or 60
# sensor.gain = 4

# Main loop reading color and printing it every second.
while True:
    # Raw data from the sensor in a 4-tuple of red, green, blue, clear light component values
    # print(sensor.color_raw)

    color = sensor.color
    color_rgb = sensor.color_rgb_bytes
    print(
        "RGB color as 8 bits per channel int: #{0:02X} or as 3-tuple: {1}".format(
            color, color_rgb
        )
    )

    # Read the color temperature and lux of the sensor too.
    temp = sensor.color_temperature
    lux = sensor.lux
    print("Temperature: {0}K Lux: {1}\n".format(temp, lux))
    # Delay for a second and repeat.
    time.sleep(1.0)

```

**Comment by jposada202020** [comment]
Thanks @silviaCC 
@caternuson Could you take a look.  Thanks :)

**Comment by silviaCC** [comment]
Well, this was ... fun! :D 
Thank you so much, @jposada202020 !  

I hope all is good now, lol

**Comment by caternuson** [comment]
Looks good! Thanks @silviaCC ! Yes, isn't pleasing the CI bots a ton of fun.

**Comment by jposada202020** [comment]
@silviaCC Thank you very much, if you need any help regarding any other PR let me know. Thanks Again for your contribution

**Pull request merged**
