### PR TITLE
change color property to use scaled color_raw values

### PR DESCRIPTION
**Pull request by FoamyGuy**
Solves #18 

Tested with: https://www.adafruit.com/product/1356

If I understand the docs in `color_raw` correctly the values should range from (0-65535). At first I tried scaling down from there to 0-255 for this but I was only getting VERY low colors or black.

I set up script to print the `color_raw` values and `1024` was the maximum value I observed for any color or clear channel. Most easily achieved by putting white paper in front of the sensor very close. 

After adjusting the scaling to use the `1024` maximum I am seeing a good range of colors when various objects are placed in front of the sensor. 

In comparison with `color_rgb_bytes` the colors this version returns tend to be similar but a bit brighter.

### CODE REVIEW

**Comment by boukeas** [comment]
> If I understand the docs in color_raw correctly the values should range from (0-65535).

According to the [datasheet](https://ams.com/documents/20143/36005/TCS3472_DS000390_3-00.pdf), the range of values depends on the integration time. The maximum value ranges from 1024 to 65536. So, correct scaling to a range of 256 values needs to take the integration time into account.

**Comment by kattni** [comment]
@FoamyGuy Did you get a chance to look into the potential integration time situation with regards to your changes?

**Comment by kattni** [comment]
@FoamyGuy Are you still interested in working on this PR?

**Comment by FoamyGuy** [comment]
@kattni I will have to bow out of this one. Sorry I didn't realize I never came back to make a follow up post here, I should have done that.

I did try looking into the integration time information in the datasheet but I'm afraid this is a bit over my head. I'm not really sure what needs to be done in the library code based on the information in datasheet.

**Comment by jposada202020** [comment]
So was reviewing all the information. I spent a fair amount of time looking for the explanation in the formulas in #18. But, no success, I propose that we close this PR as it will not solve the root cause of the problem, and it will not solve the issue. 
Let me know your suggestions. Thanks
@kattni and @FoamyGuy

**Comment by silviaCC** [comment]
I agree with @jposada202020, I don't think these changes are necessary. 
I explained my findings about the issue in #18  comments. 

@kattni  @FoamyGuy

**Comment by jposada202020** [comment]
@FoamyGuy PR #37 was merged. Do you agree to close this PR?. please see comments in issue #18

**Comment by FoamyGuy** [comment]
Yep. Thank you @silviaCC

**Pull request closed without merging**
